[lib]
crate-type = [ "staticlib" ]

[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.5.2"
x86 = "0.52.0"

[profile.release]
lto = true
opt-level = 2
strip = true
