name: SayoriOS Buildbot

# Контроль событий при которых будет сборка
on:
  # В нашем случае это push в ветку master
  push:
    branches: [ "master" ]
  #pull_request:
  #  tags:
  #      - "v*"
  #  branches: [ "master" ]
  # Позволяет запускать этот рабочий процесс вручную на вкладке Actions
  workflow_dispatch:

# Выполнение рабочего процесса состоит из одного или нескольких заданий, которые могут выполняться последовательно или параллельно
jobs:
  build:
    #  Все будет работать на последней версии Ubuntu
    runs-on: ubuntu-latest

    # Шаги представляют собой последовательность задач, которые будут выполняться как часть задания
    steps:
      - uses: actions/checkout@v3

      - name: Just lists all version of clang
        run: sudo apt list "clang-*"

      # Установка зависимостей
      - name: Установка программного обеспечения
        run: |
          sudo apt install python3 build-essential xorriso grub-pc-bin mtools llvm lld fasm zip doxygen
          
      # Запуск сборки ядра
      - name: Компиляция ядра
        run: python3 build.py kernel

      # Запуск сборки ПО
      - name: Компиляция программ
        run: python3 build.py apps

      # Создание дистрибутива
      - name: Компиляция ISO
        run: python3 build.py iso isol
      
      # Запуск Doxygen
      - name: Генерация документации
        run: |
          rm -rf docs/doxygen/
          sudo doxygen Doxyfile
          ls docs/doxygen/
          ls

      # Проверка релиза
      - name: Проверка публикации
        run: |
          echo "done!"
          ls isodir/boot/
          ls
        
      # Публикация документации
      - name: Принимаем изменения
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Github
          author_email: github@example.com
          message: 'Документация: Обновление документации с помощью doxygen [Автосборка]'
          add: 'docs/doxygen/html/*'

      # Публикация релиза
      - name: Публикуем нестабильный релиз
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.SAYORI }}"
          automatic_release_tag: "latest-unstable"
          prerelease: true
          title: "[Автосборка] Нестабильный релиз"
          description: "Внимание! Данный релиз собран из последних изменений в ядре! Это не окончательная версия содержит ошибки и не рекомендуется к запуску без проверки на виртуальной машине."
          files: |
            LICENSE
            SayoriOS.iso
            isodir/boot/initrd.tar
            isodir/boot/kernel.elf
            docs/doxygen/rtf/refman.rtf
