name: 🤖 Автоматическая сборка

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Just lists all version of clang
        run: sudo apt list "clang-*"

      - name: Step 1 - Update version build
        env:
          TOKEN: ${{ secrets.SAYORI_UPDATE }}
        run: |
            curl -d "uid=2&act=download.kernel.buildup" -X POST https://sayorios.piminoff.ru/api/index.php?token="$TOKEN"
